Repository shipgirlproject/Shoukaku, pull requests merged in 2020-08, with the labels that each got.

#15 Fixed ShoukakuRest#resolve optional search param
  index.d.ts
Labels: documentation

#16 Implement bug fix. See below.
  src/guild/ShoukakuPlayer.js
Labels: enhancement

#18 fix: #17
  src/guild/ShoukakuPlayer.js
Labels: bug, enhancement
