Repository shipgirlproject/Shoukaku, pull requests merged in 2021-08, with the labels that each got.

#58 fix: typings
  types/guild/ShoukakuConnection.d.ts
Labels: bug

#42 V2 refactor
  .eslintrc.yml
  .github/CODEOWNERS
  .github/workflows/docs.yml
  CHANGELOGS.MD
  README.md
  assets/cover.jpg
  assets/cover.png
  docma.json
  docs/content/readme.html
  docs/css/styles.css
  docs/index.html
  docs/js/docma-web.js
  index.d.ts
  index.js
  package.json
  src/Constants.js
  src/Shoukaku.js
  src/Utils.js
  src/constants/ShoukakuConstants.js
  src/constants/ShoukakuError.js
  src/constants/ShoukakuFilter.js
  src/constants/ShoukakuTimeout.js
  src/guild/ShoukakuConnection.js
  src/guild/ShoukakuLink.js
  src/guild/ShoukakuPlayer.js
  src/libraries/Libraries.js
  src/libraries/README.md
  src/libraries/wrappers/DiscordJS.js
  src/libraries/wrappers/Eris.js
  src/node/ShoukakuQueue.js
  src/node/ShoukakuRest.js
  src/node/ShoukakuRouter.js
  src/node/ShoukakuSocket.js
  src/rest/ShoukakuRest.js
  src/struct/ShoukakuFilter.js
  src/struct/ShoukakuStats.js
  src/struct/ShoukakuTrack.js
  src/struct/ShoukakuTrackList.js
  src/util/ShoukakuUtil.js
  types/Constants.d.ts
  types/README.md
  types/Shoukaku.d.ts
  types/Utils.d.ts
  types/guild/ShoukakuConnection.d.ts
  types/guild/ShoukakuPlayer.d.ts
  types/libraries/Constants.d.ts
  types/libraries/Libraries.d.ts
  types/libraries/README.md
  types/libraries/wrappers/DiscordJS.d.ts
  types/libraries/wrappers/Eris.d.ts
  types/node/ShoukakuQueue.d.ts
  types/node/ShoukakuRest.d.ts
  types/node/ShoukakuRouter.d.ts
  types/node/ShoukakuSocket.d.ts
  types/struct/ShoukakuFilter.d.ts
  types/struct/ShoukakuStats.d.ts
Labels: documentation, enhancement

#66 Fix(ShoukakuSocket): send voiceUpdate when already reconnected
  docs/content/readme.html
  docs/js/docma-web.js
  src/guild/ShoukakuPlayer.js
  src/node/ShoukakuSocket.js
  types/node/ShoukakuSocket.d.ts
Labels: bug, enhancement
