Repository shipgirlproject/Shoukaku, pull requests merged in 2021-02, with the labels that each got.

#27 feat: searching on youtube music
  index.d.ts
  src/rest/ShoukakuRest.js
  src/util/ShoukakuUtil.js
Labels: enhancement

#28 Fix issues in Shoukaku player not updating filters correctly
  src/guild/ShoukakuPlayer.js
Labels: bug

#29 feat: add node secure protocol options.
  docs/content/readme.html
  docs/js/docma-web.js
  index.d.ts
  src/constants/ShoukakuConstants.js
  src/node/ShoukakuSocket.js
  src/rest/ShoukakuRest.js
Labels: documentation, enhancement
