Repository shipgirlproject/Shoukaku, pull requests merged in 2023-05, with the labels that each got.

#144 Fix typo in src/node/Node.ts
  src/node/Node.ts
Labels: documentation

#146 Set custom timeout for connection to discord
  README.md
  src/Shoukaku.ts
  src/guild/Connection.ts
Labels: enhancement

#145 Fix player not moved correctly if not playing
  src/guild/Player.ts
Labels: question

#148 Fix voiceConnectionTimeout option is not applied correctly
  src/Constants.ts
  src/guild/Connection.ts
Labels: bug fix

#149 Fix typo on emit resume event
  src/guild/Player.ts
Labels: bug fix
