Repository shipgirlproject/Shoukaku, pull requests merged in 2023-01, with the labels that each got.

#119 `Added plugin support`
  README.md
Labels: documentation

#122 Fix listeners leak
  src/guild/Connection.ts
Labels: bug, enhancement

#121 Remove useless await, it will use less memory
  src/node/Rest.ts
Labels: enhancement

#129 Added rawEvents on node in v3
  src/Shoukaku.ts
  src/node/Node.ts
Labels: enhancement

#127 Added rawEvents on node in v4
  src/Shoukaku.ts
  src/node/Node.ts
Labels: enhancement
